### ISSUE TITLE
0.2 Alpha Buttons (Reset) affiliation not clear

### ISSUE THREAD

**Issue by Mandi1987** [pediRAM/GeNSIS#1]
Reset button for installer name is an example

**Comment by pediRAM** [comment]
> Reset button for installer name is an example

Do you have any idea why the affiliation of buttons are not clear?
Any idea how it would improve the UX?

**Comment by pediRAM** [comment]
![grafik](https://github.com/pediRAM/GeNSIS/assets/11803923/ae32fcbb-3614-4286-a0fe-cf2d9449effe)

It should be now clear enough where the "Reset" button belongs to... hopefully :-)
