### ISSUE TITLE
Alpha 0.2 custom none/multiple shortcut(s)

### ISSUE THREAD

**Issue by Mandi1987** [pediRAM/GeNSIS#4]
What if someone does not want to create shortcut, and what about creating multiple shortcuts for multiple apps in one installer?

**Comment by pediRAM** [comment]
Normally people install applications or services, but no folder or file!

The philosophy, aim and intention behind the GeNSIS are following thoughts and rules:
- Simplicity
- Sticking to conventions
- Deleting lines, Copy & Paste, but also modification of existing and well commented code, are easier than writing script/code from scratch
- Provide/Generate 80% of stuff, which 80% of installers have to do in nearly 80% of time/situations for 80% of applications/services

In the new version, the user can choose to create shortcuts or not during installation (by yes-no-dialog).

If shortcuts should not be created --> just remove those lines.

If more shortcuts have to be created --> Copy & Paste is the best choice
