### ISSUE TITLE
Alpha 0.2 NSIS breaks compilation because empty folders

### ISSUE THREAD

**Issue by Mandi1987** [pediRAM/GeNSIS#5]
When compiling nsi script, NSIS compiler breaks compilation everytime an empty folder is found (lines starting with "File /r" command for recursive folder copy actions).

**Comment by pediRAM** [comment]
> When compiling nsi script, NSIS compiler breaks compilation everytime an empty folder is found (lines starting with "File /r" command for recursive folder copy actions).

Will try to replicate and find out why

**Comment by pediRAM** [comment]
Fixed by creating folder instead copying for empty source folders
